name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Platform: Win32
      Configuration: Release-Static
      BuildType: ci
      VERSION_MAJOR: 1
      VERSION_MINOR: 12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
    
    - name: Set VERSION_REVISION and VERSION_BUILD variables
      run: |
        echo "::set-env name=VERSION_REVISION::$env:GITHUB_RUN_ID"
        echo "::set-env name=VERSION_BUILD::$env:GITHUB_RUN_NUMBER"

    - name: Set VERSION variable
      run: echo "::set-env name=VERSION::$env:VERSION_MAJOR.$env:VERSION_MINOR.$env:VERSION_REVISION-$env:BuildType$env:VERSION_BUILD"
    
    - name: Build pjsip
      run: msbuild pjproject-1.8.10\pjproject-vs8.sln -t:Build -p:Configuration=$env:Configuration -p:Platform=$env:Platform -p:DefineConstants="VERSION_MAJOR=$env:VERSION_MAJOR;VERSION_MINOR=$env:VERSION_MINOR;VERSION_REVISION=$env:VERSION_REVISION;VERSION_BUILD=$env:VERSION_BUILD"

    - name: Add VERSION file
      run: $env:VERSION > pjsipdll\bin\VERSION

    - name: Upload build artifacts - pjsipdll
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pjsipdll
        path: pjsipdll\bin

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Build NuGet package
      run: nuget pack pjsipdll\build\*.nuspec -Version $env:VERSION -Properties Configuration=$env:Configuration -OutputDirectory pjsipdll\nuget

    - name: Upload nuget packages
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pjsipdll-nuget
        path: pjsipdll\nuget
